### ISSUE TITLE
Mod conflict with ExoGenesis

### ISSUE THREAD

**Issue by alexNecroJack** [MinRi2/MinerTools#11]
Hello, when I enable this mod along [[ExoGenesis](https://github.com/AureusStratus/ExoGenesis)](https://github.com/AureusStratus/ExoGenesis), the game crashes.

Bug report:
```
Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Windows 8.1 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 2024mb
Cores: 4
Mods: additional-content:0.4.1, animalia:java 1.0, betamindy:1.1, cyber-io:5.1, distributor:1.1, exogenesis:[blue]1.9.1, extra-utilities:1.1.5.2, informatis:1.9.1, me:2.3, mi2-utilities-java:1.4.2c, miner-tools:1.7.5, new-horizon:0.4.8, production-mod:A4.4.3, prog-mats:27.3, sapphirium:16.0, trade-it:3.0, trade-terminals:2.0.1, uaw:v0.8.3, unity:0.2-youngcha.3.3

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: contentinit
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:215)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: contentinit
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:104)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot read field "amount" because "this.coolant" is null
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:102)
	... 9 more
Caused by: java.lang.NullPointerException: Cannot read field "amount" because "this.coolant" is null
	at mindustry.world.blocks.defense.turrets.LaserTurret.setStats(LaserTurret.java:30)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:85)
	at MinerTools.override.stats.MStats$StatOverride.override(MStats.java:22)
	at MinerTools.content.Contents.initBlocks(Contents.java:68)
	at MinerTools.content.Contents.init(Contents.java:22)
	at MinerTools.MinerTools.lambda$new$0(MinerTools.java:31)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.core.ContentLoader.init(ContentLoader.java:89)
	at mindustry.ClientLauncher.lambda$setup$7(ClientLauncher.java:175)
	at arc.assets.AssetManager$1.loadAsync(AssetManager.java:328)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:52)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:16)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by MinRi2** [comment]
Fixed.
