### ISSUE TITLE
Crash on every chat message

### ISSUE THREAD

**Issue by superdinmc** [MinRi2/MinerTools#5]
```log
[E] java.lang.ClassCastException: class mindustry.ui.fragments.ChatFragment$ChatMessage cannot be cast to class java.lang.String (mindustry.ui.fragments.ChatFragment$ChatMessage is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at MinerTools.ui.tables.floats.ChatTable.resetMessages(ChatTable.java:203)
        at MinerTools.ui.tables.floats.ChatTable.update(ChatTable.java:269)
        at arc.scene.Element.act(Element.java:79)
        at arc.scene.Group.act(Group.java:37)
        at arc.scene.Group.act(Group.java:41)
        at arc.scene.Scene.act(Scene.java:198)
        at arc.scene.Scene.act(Scene.java:143)
        at mindustry.core.UI.update(UI.java:152)
        at arc.ApplicationCore.update(ApplicationCore.java:37)
        at mindustry.ClientLauncher.update(ClientLauncher.java:256)
        at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:58)
```

**Comment by MinRi2** [comment]
I will check it when i am available.
